const adjacent=document.createElement('section');
adjacent.id='adjacent-example';
adjacent.className='section';
adjacent.innerHTML=`<div class="wrap"><div class="eyebrow">Adjacent-site engineering example</div><h2>Why put plastic voids inside a concrete slab?</h2><p class="lede">These three older photographs are from the neighboring project, not HELIX 3. They are included only as a teaching example because they show an unusual structural idea especially clearly.</p><div class="twocol" style="align-items:start;margin-top:28px"><div class="card"><div class="status observed">Observed</div><h3>Plastic void formers inside dense reinforcement</h3><p>The photographs show repeated hollow plastic modules arranged within a heavily reinforced slab zone before concrete placement. Concrete is then placed around the modules while the plastic remains embedded.</p><p><b>Likely purpose:</b> this is a voided reinforced-concrete slab system. The voids remove concrete from regions where solid concrete may contribute relatively little structurally, reducing dead load while preserving a deep structural zone.</p><p><b>Unknown:</b> the proprietary system, final slab thickness, reinforcement design and exact structural role cannot be confirmed from the photographs alone.</p></div><div class="card"><h3>Student takeaway</h3><p>A slab can look extraordinarily thick without being solid concrete throughout. Engineers can deliberately place lightweight voids inside a deep slab to reduce self-weight, material use and foundation demand while maintaining the geometry needed for strength and stiffness.</p><p class="note"><b>Boundary rule:</b> this example belongs to the adjacent development and is deliberately kept separate from the HELIX 3 construction timeline.</p></div></div><div class="gallery" style="margin-top:28px">${['IMG_6227.JPG','IMG_6228.JPG','IMG_6229.JPG'].map((f,i)=>`<article class="photo"><img loading="lazy" src="images/adjacent/${f}" alt="Adjacent-site voided slab construction view ${i+1}"><div class="cap"><span class="badge">Adjacent site</span><h3>${['Void formers before the pour','Voids nested within reinforcement','Deep slab zone ready for concrete'][i]}</h3><small>Educational reference only — not HELIX 3.</small></div></article>`).join('')}</div></div>`;
const updates=document.querySelector('#updates');
if(updates) updates.before(adjacent);
const navWrap=document.querySelector('.nav .wrap');
if(navWrap&&!navWrap.querySelector('a[href="#adjacent-example"]')){const link=document.createElement('a');link.href='#adjacent-example';link.textContent='Adjacent example';const updatesLink=[...navWrap.querySelectorAll('a')].find(a=>a.getAttribute('href')==='#updates');if(updatesLink)navWrap.insertBefore(link,updatesLink);else navWrap.appendChild(link);}
adjacent.querySelectorAll('img').forEach(img=>img.onclick=()=>{const lb=document.querySelector('.lightbox');if(!lb)return;const im=lb.querySelector('img');im.src=img.src;im.alt=img.alt;lb.classList.add('open');});
