const guide=document.createElement('section');
guide.id='field-guide';
guide.className='section';
const item=(title,status,statusClass,body,img='')=>`<details class="guide-item"><summary><span class="guide-title">${title}</span>${status?`<span class="guide-status ${statusClass}">${status}</span>`:''}<span class="guide-chevron">+</span></summary><div class="guide-body">${img?`<img src="${img}" alt="${title}">`:''}${body}</div></details>`;
const vendors=[
item('Silvi Materials','Confirmed','observed','<p><b>Observed role:</b> ready-mix concrete supply. A queue of Silvi mixer trucks was photographed on September 3 while foundation concreting was underway.</p><p><b>Student takeaway:</b> large placements depend on dispatch, travel time, truck spacing, pump capacity and continuity of supply, not just the concrete mix itself.</p>','images/originals/IMG_5287.jpeg'),
item('Foundation drilling contractor','To be identified','unknown','<p>The specialized crew operating the rotary drilling rigs, casing equipment and shaft tools is clearly central to the foundation program, but the contractor name has not yet been confirmed from the photographs.</p>'),
item('Concrete pumping contractor','To be identified','unknown','<p>The boom-pump operator is visible in the construction sequence, but the company identity is not yet confirmed. A future close-up of truck doors, booms or site signage may resolve it.</p>')];
const equipment=[
item('Rotary foundation drilling rig','','','<p>Provides the torque, crowd force and vertical guidance needed to excavate deep drilled shafts. The rig works through the steel casing and continues below it.</p>','images/originals/62D6CEC3-775D-41B0-874A-ADED80A6CF9A.jpeg'),
item('Casing installation system','','','<p>A large gripping, rotating or vibratory system advances steel casing into weak, wet upper soils before deeper drilling begins.</p>','images/originals/F2B02F55-7AF2-4A99-880A-00C8F179C188.jpeg'),
item('Kelly bar and drilling bucket','','','<p>The telescoping Kelly bar transmits torque and vertical force. Buckets and clean-out tools remove excavated material from the bottom of the shaft.</p>','images/originals/IMG_5D40E3D5-A099-49F3-A4B7-6AEC3D35B97B.jpeg'),
item('Concrete boom pump','','','<p>Outriggers stabilize the truck while the articulated boom positions the delivery line over a shaft. Pumping lets concrete be delivered rapidly and continuously to a precise location.</p>','images/originals/4B4CCB4A-4C0A-4DE3-A87B-93A84761881B.jpeg'),
item('Reinforcing cage and lifting operation','','','<p>The cylindrical steel cage is prefabricated horizontally, lifted vertically and guided into the bore. Its geometry provides longitudinal and confinement reinforcement to the shaft.</p>','images/originals/IMG_D775CA6B-DD38-4B38-BBCA-A8D17FBA2535.jpeg'),
item('Hydraulic excavators','','','<p>Excavators handle mass excavation, spoil movement, grading and access preparation while specialist foundation work continues elsewhere on the site.</p>','images/originals/IMG_5288.jpeg')];
const technologies=[
item('Drilled-shaft foundations','Observed','observed','<p>Large-diameter shafts transfer building loads deep into stronger ground. Different visible shaft and cage sizes suggest more than one design capacity.</p>'),
item('Wet-hole construction','Observed','observed','<p>Drilling extends below groundwater. Water or drilling fluid occupies the bore during construction and is displaced as concrete rises from below.</p>'),
item('Steel casing for bore stability','Observed','observed','<p>Casing supports troublesome upper ground and helps keep the bore open while the drilling rig advances deeper.</p>'),
item('Continuous pumped concrete placement','Observed','observed','<p>Concrete is delivered through a pump while mixer trucks are sequenced to reduce interruptions during major shaft placements.</p>'),
item('Groundwater-control well with filter pack','Likely','likely','<p>A smaller pipe was lowered inside a small steel casing and the annulus filled with clean coarse stone. This is consistent with a dewatering or groundwater-control installation, but we are waiting for well-head equipment to confirm it.</p>','images/originals/IMG_5290.jpeg'),
item('Concurrent construction logistics','Observed','observed','<p>Excavation, drilling, cage handling and concrete supply are occurring in parallel. The site shows how construction engineering coordinates space, equipment and schedule, not just structural design.</p>')];
guide.innerHTML=`<div class="wrap"><div class="eyebrow">Student field guide</div><h2>Vendors, equipment and technologies</h2><p class="lede">A compact field guide for civil and structural engineering students. Tap any item to open its explanation.</p><p class="note"><b>Identification rule:</b> company and equipment-manufacturer names are added only when the photographs clearly support them. Otherwise we describe the function rather than guess.</p><div class="guide-section"><h3>Vendors observed</h3><div class="guide-grid">${vendors.join('')}</div></div><div class="guide-section"><h3>Equipment observed on site</h3><div class="guide-grid">${equipment.join('')}</div></div><div class="guide-section"><h3>Construction technologies</h3><div class="guide-grid">${technologies.join('')}</div></div><div class="guide-questions"><b>For students:</b> with every new photograph, ask what the operation does, what load path it serves, what soil or groundwater condition it responds to, which works are temporary versus permanent, and what must happen next.</div></div>`;
const interpretation=document.querySelector('#interpretation');
if(interpretation) interpretation.before(guide);
const navWrap=document.querySelector('.nav .wrap');
if(navWrap&&!navWrap.querySelector('a[href="#field-guide"]')){const link=document.createElement('a');link.href='#field-guide';link.textContent='Field guide';const interpretationLink=[...navWrap.querySelectorAll('a')].find(a=>a.getAttribute('href')==='#interpretation');if(interpretationLink)navWrap.insertBefore(link,interpretationLink);else navWrap.appendChild(link);}
