const guide=document.createElement('section');
guide.id='field-guide';
guide.className='section';
const item=(title,status,statusClass,body,img='')=>`<details class="guide-item"><summary><span class="guide-title">${title}</span>${status?`<span class="guide-status ${statusClass}">${status}</span>`:''}<span class="guide-chevron">+</span></summary><div class="guide-body">${img?`<img loading="lazy" decoding="async" src="${img}" alt="${title}">`:''}${body}</div></details>`;
const vendors=[
item('Silvi Materials','Confirmed','observed','<p><b>Observed role:</b> ready-mix concrete supply. A queue of Silvi mixer trucks was photographed on September 3 while foundation concreting was underway.</p><p><b>Student takeaway:</b> large placements depend on dispatch, travel time, truck spacing, pump capacity and continuity of supply, not just the concrete mix itself.</p>','images/originals/IMG_5287.jpeg'),
item('Foundation drilling contractor','To be identified','unknown','<p>The specialized crew operating the rotary drilling rigs, casing equipment and shaft tools is clearly central to the foundation program, but the contractor name has not yet been confirmed from the photographs.</p>'),
item('Concrete pumping contractor','To be identified','unknown','<p>The boom-pump operator is visible in the construction sequence, but the company identity is not yet confirmed. A future close-up of truck doors, booms or site signage may resolve it.</p>')];
const equipment=[
item('Dump trucks and soil haulage','Observed','observed','<p><b>Observed:</b> The September 11 morning photographs show a line of dump trucks and a CAT 330D loading soil into a truck body.</p><p><b>Likely role:</b> Removal of excavated material from the site. Loading, truck access and turnaround must work together to sustain excavation.</p><p><b>Unknown:</b> Truck capacities, cycle times, daily quantities, haul destination and whether the queue represents planned staging or a delay. A still photograph cannot measure production.</p>','images/web/IMG_5326.jpg'),
item('Rotary foundation drilling rig','Earlier phase','observed','<p>Provides the torque, crowd force and vertical guidance needed to excavate deep drilled shafts. Earlier photographs show the rig working through steel casing. It is visible in the September 4 overview, absent from the September 10 overview, and reported gone by the observer on September 11. This does not confirm that every shaft is complete.</p>','images/originals/62D6CEC3-775D-41B0-874A-ADED80A6CF9A.jpeg'),
item('Casing installation system','','','<p>A large gripping, rotating or vibratory system advances steel casing into weak, wet upper soils before deeper drilling begins.</p>','images/originals/F2B02F55-7AF2-4A99-880A-00C8F179C188.jpeg'),
item('Kelly bar and drilling bucket','','','<p>The telescoping Kelly bar transmits torque and vertical force. Buckets and clean-out tools remove excavated material from the bottom of the shaft.</p>','images/originals/IMG_5D40E3D5-A099-49F3-A4B7-6AEC3D35B97B.jpeg'),
item('Concrete boom pump','','','<p>Outriggers stabilize the truck while the articulated boom positions the delivery line over a shaft. Pumping lets concrete be delivered rapidly and continuously to a precise location.</p>','images/originals/4B4CCB4A-4C0A-4DE3-A87B-93A84761881B.jpeg'),
item('Reinforcing cage and lifting operation','','','<p>The cylindrical steel cage is prefabricated horizontally, lifted vertically and guided into the bore. Its geometry provides longitudinal and confinement reinforcement to the shaft.</p>','images/originals/IMG_D775CA6B-DD38-4B38-BBCA-A8D17FBA2535.jpeg'),
item("CAT 390F \u2014 large crawler excavator","Model observed","observed","<p><b>Observed:</b> The large machine in IMG_6258.JPG is a CAT 390F; the marking is also clear in September 10 IMG_6247.JPG.</p><p><b>Likely role:</b> Bulk excavation and moving large volumes of soil.</p><p><b>Unknown:</b> Operating weight, bucket capacity and exact configuration.</p>","images/originals/IMG_6258.JPG"),
item("CAT 330D \u2014 crawler excavator","Model observed","observed","<p><b>Observed:</b> CAT 330D markings are visible in the close views. This machine is smaller than the 390F, but it is not a mini excavator.</p><p><b>Likely role:</b> General excavation and material handling.</p><p><b>Unknown:</b> The precise attachment specification and operating configuration.</p>","images/originals/IMG_6259.JPG"),
item("Volvo \u2014 crawler excavator","Brand observed","observed","<p><b>Observed:</b> VOLVO is legible on the boom. The machine has a digging bucket and an articulated hydraulic boom.</p><p><b>Likely role:</b> Excavation with maneuvering space constrained by shafts and other machines.</p><p><b>Unknown:</b> Exact model; do not infer it from brand, color or apparent size alone.</p>","images/originals/IMG_6257.JPG"),
item("CAT \u2014 working between casings","Brand observed","observed","<p><b>Observed:</b> A CAT excavator works in the corridor beside casings 49 and 40. It is larger than the mini machine shown in the next frame.</p><p><b>Likely role:</b> Controlled excavation between established shaft locations.</p><p><b>Unknown:</b> Exact model and rated size class.</p>","images/originals/IMG_6254.JPG"),
item("CAT \u2014 smaller excavator with blade","Brand observed","observed","<p><b>Observed:</b> A separate CAT machine near casings 27 and 14 has crawler tracks and a visible front blade.</p><p><b>Likely role:</b> Localized digging and working-platform grading.</p><p><b>Unknown:</b> Exact model; the blade alone does not establish an official size class.</p>","images/originals/IMG_6256.JPG"),
item("CAT \u2014 mini excavator","Brand observed","observed","<p><b>Observed:</b> A small CAT machine fits between the casings beside the boundary. This is the appropriate photograph for the mini-excavator entry.</p><p><b>Likely role:</b> Detailed excavation in narrow gaps.</p><p><b>Unknown:</b> Exact model and rated operating weight.</p>","images/originals/IMG_6255.JPG")];
const technologies=[
item('Drilled-shaft foundations','Observed','observed','<p>Large-diameter shafts transfer building loads deep into stronger ground. Different visible shaft and cage sizes suggest more than one design capacity.</p>'),
item('Wet-hole construction','Observed','observed','<p>Drilling extends below groundwater. Water or drilling fluid occupies the bore during construction and is displaced as concrete rises from below.</p>'),
item('Steel casing for bore stability','Observed','observed','<p>Casing supports troublesome upper ground and helps keep the bore open while the drilling rig advances deeper.</p>'),
item('Perimeter excavation support / shoring','Observed','observed','<p>Observed: steel posts and horizontal lagging retain the boundary as excavation exposes more casing height. The observer identifies the strongly supported boundaries as the north and south walls. Likely: the increasing retained height makes lateral earth support increasingly important. Unknown: the design loads, embedment, anchors and measured wall movement. The photographs do not establish the system’s capacity. On a constrained urban site, these temporary works protect the excavation boundary and help control movement near streets, utilities and neighboring property.</p>','images/originals/IMG_6264.JPG'),
item('Continuous pumped concrete placement','Observed','observed','<p>Concrete is delivered through a pump while mixer trucks are sequenced to reduce interruptions during major shaft placements.</p>'),
item('Groundwater-control well with filter pack','Likely','likely','<p>A smaller pipe was lowered inside a small steel casing and the annulus filled with clean coarse stone. This is consistent with a dewatering or groundwater-control installation, but we are waiting for well-head equipment to confirm it.</p>','images/originals/IMG_5290.jpeg'),
item('Concurrent construction logistics','Observed','observed','<p>Earlier photographs documented excavation, drilling, cage handling and concrete supply in parallel. By September 11 the observer reports the drilling rig gone, while excavation and material handling continue. The site shows how construction engineering coordinates space, equipment and schedule, not just structural design.</p>')];
guide.innerHTML=`<div class="wrap"><div class="eyebrow">Student field guide</div><h2>Vendors, equipment and technologies</h2><p class="lede">A compact field guide for civil and structural engineering students. Tap any item to open its explanation.</p><p class="note"><b>Identification rule:</b> company and equipment-manufacturer names are added only when the photographs clearly support them. Otherwise we describe the function rather than guess. The September 11 batch shows six distinct excavators across several views; repeated photographs are not additional machines. This is a count of individual machines, not six confirmed models or six equipment classes. The mini CAT and the larger CAT beside casings 49/40 appear together at the edges of IMG_6254 and IMG_6255; the blade-equipped CAT occupies a separate area near casings 27/14. Size descriptions are visual comparisons, not rated weight classes.</p><div class="guide-section"><h3>Vendors observed</h3><div class="guide-grid">${vendors.join('')}</div></div><div class="guide-section"><h3>Equipment across the journal</h3><div class="guide-grid">${equipment.join('')}</div></div><div class="guide-section"><h3>Construction technologies</h3><div class="guide-grid">${technologies.join('')}</div></div><div class="guide-questions"><b>For students:</b> with every new photograph, ask what the operation does, what load path it serves, what soil or groundwater condition it responds to, which works are temporary versus permanent, and what must happen next.</div></div>`;
const interpretation=document.querySelector('#interpretation');
if(interpretation) interpretation.before(guide);
const navWrap=document.querySelector('.nav .wrap');
if(navWrap&&!navWrap.querySelector('a[href="#field-guide"]')){const link=document.createElement('a');link.href='#field-guide';link.textContent='Field guide';const interpretationLink=[...navWrap.querySelectorAll('a')].find(a=>a.getAttribute('href')==='#interpretation');if(interpretationLink)navWrap.insertBefore(link,interpretationLink);else navWrap.appendChild(link);}

guide.querySelectorAll("img").forEach(img=>img.addEventListener("click",()=>openLightbox(img.src,img.alt)));
