(()=>{
 const section=document.createElement('section');
 section.id='update-oct6';section.className='section';section.dataset.updateDate='2026-10-06';
 section.innerHTML=`<div class="wrap"><div class="eyebrow">Field update</div><h2>The giant excavator leaves.<br>Aggregate reaches the lowest cuts.</h2><p class="lede">October 6 records two changes: the large CAT crawler excavator leaves on a heavy-haul lowboy, and the observer reports aggregate being placed over the lowest parts of the excavation. The crane, smaller excavators and eastern site office remain in the wide views.</p>
 <div class="cutting-grid"><figure><img loading="lazy" src="images/annotated/IMG_0140.svg" alt="Numbered overhead photograph of the large CAT excavator on a lowboy: folded boom, low deck, rear axle group and tractor"><figcaption>The clearest view of the transport arrangement. <a class="photo-original" href="images/originals/IMG_0140.jpeg">View original photograph</a></figcaption></figure><article class="card"><div class="status observed">Photographed and observer confirmed</div><h3>1 · Boom folded for the journey</h3><p>The machine is a tracked hydraulic excavator, rather than a bulldozer. Its long boom and stick are folded along the trailer. The observer confirms that this giant machine has now left the site.</p><h3>2–4 · A low deck and many axles</h3><p>The tracks sit on the trailer's low central deck, behind the tractor and ahead of the rear axle group. The lowered deck reduces overall transport height; the multiple axles distribute the heavy load. The overhead view makes the articulated tractor-and-trailer arrangement especially clear.</p><p>These photographs show the loaded haul and departure, but not the loading operation. The trailer's exact loading mechanism, machine weight and model are not established here.</p></article></div>
 <div class="grid" style="margin-top:28px"><figure class="card" style="margin:0"><img loading="lazy" src="images/originals/IMG_0139.jpeg" alt="Loaded CAT excavator on a red lowboy alongside the site boundary" style="width:100%;height:auto"><figcaption>Alongside the site: the excavator is already on the lowboy.</figcaption></figure><figure class="card" style="margin:0"><img loading="lazy" src="images/originals/IMG_0134.jpeg" alt="Tractor and lowboy carrying the CAT excavator near the far intersection" style="width:100%;height:auto"><figcaption>At the far intersection: the heavy-haul combination negotiates the narrow street.</figcaption></figure><figure class="card" style="margin:0"><img loading="lazy" src="images/originals/IMG_0133.jpeg" alt="Evening view of the CAT excavator and haul vehicle farther along the street" style="width:100%;height:auto"><figcaption>Evening departure view: the giant CAT is farther along the street.</figcaption></figure></div>
 <div class="cutting-grid" style="margin-top:36px"><figure><img loading="lazy" src="images/annotated/IMG_0136.svg" alt="Site overview marking the lowest excavation area, exposed shaft heads, crane, foreground aggregate and eastern office"><figcaption>The lower excavation and the foreground office pad are separate areas. Number 1 marks the lower pocket discussed by the observer, not a surveyed boundary of stone coverage. <a class="photo-original" href="images/originals/IMG_0136.jpeg">View original photograph</a></figcaption></figure><article class="card"><div class="status observed">Observer report and visible context</div><h3>1 · Aggregate in the lowest excavation</h3><p>The observer directly reports crews covering the lowest parts of the excavation with aggregate. The wide views locate that work among exposed drilled-shaft heads and projecting reinforcement. Wet patches remain visible; a dark surface in a distant photograph should not automatically be labeled stone.</p><h3>2–5 · Work continues after the giant leaves</h3><p>The shaft heads remain exposed. A mobile crane stands beside the pit with its boom extended and outriggers deployed. The foreground has gray aggregate beside a Volvo excavator and a roller, while the new mobile office remains at the eastern end nearest the observer.</p><div class="status likely">Engineering interpretation</div><p>Aggregate can provide a firmer, more even working base and, where its grading permits, assist drainage. Here it is consistent with preparing the lower excavation for subsequent foundation work. Its thickness, grading and final role are unknown; the photographs do not yet establish a drainage layer, waterproofing, blinding concrete or the final cap/mat design.</p></article></div>
 <details class="card" style="margin-top:24px"><summary>Another full-site view</summary><figure style="margin:16px 0 0"><img loading="lazy" src="images/originals/IMG_0138.jpeg" alt="Portrait overview of exposed foundation shafts, crane, aggregate stockpile and eastern mobile office" style="width:100%;height:auto"><figcaption>The portrait frame preserves the wider site context.</figcaption></figure></details>
 <p class="note" style="margin-top:24px"><b>Next clues:</b> broader stone coverage, any leveling or blinding layer, and horizontal reinforcement linking the shaft heads. One excavator's departure does not establish that all excavation is complete.</p><p class="note">General background: <a href="https://www.fhwa.dot.gov/publications/research/infrastructure/pavements/97148/073.cfm" target="_blank" rel="noopener">FHWA on granular bases and drainage</a>. This describes general material functions, not the HELIX 3 foundation specification.</p></div>`;
 document.querySelector('#update-oct5').before(section);
 const nav=document.querySelector('.nav .wrap');const link=document.createElement('a');link.href='#update-oct6';link.textContent='October 6';nav.insertBefore(link,nav.querySelector('a'));
 section.querySelectorAll('img').forEach(img=>img.addEventListener('click',()=>openLightbox(img.src,img.alt)));
})();
