(()=>{
 const section=document.createElement('section');
 section.id='update-oct5';section.className='section';section.dataset.updateDate='2026-10-05';
 section.innerHTML=`<div class="wrap"><div class="eyebrow">Field update</div><h2>A crane above the pit.<br>A new office at the eastern end.</h2><p class="lede">October 5 brings a mobile crane set up for lifting, a new site office nearest the observer, and an increasingly legible excavation footprint. The observer confirms that the plastic sheet and rolled gravel photographed on October 2 formed the surface on which the mobile office was placed.</p>
 <div class="cutting-grid"><figure><img loading="lazy" src="images/annotated/IMG_0120.svg" alt="Eight numbered features: mobile crane, new eastern office, shaft heads, reinforcement, excavators, retaining wall, near excavation edge and roller"><figcaption>Full-site overview. Numbered labels identify visible features; the office location and use of its prepared base are observer-confirmed. <a class="photo-original" href="images/originals/IMG_0120.jpeg">View original photograph</a></figcaption></figure><div class="haulage-copy"><article class="card"><div class="status observed">Visible in the photographs</div><h3>1 · Crane set up for lifting</h3><p>A wheeled mobile crane has its telescopic boom extended and outriggers deployed onto support pads. A yellow hook block hangs over the excavation. No identifiable load is attached in these stills, so its immediate lifting task remains unknown.</p><h3>3–6 · Work at several levels</h3><p>Exposed concrete drilled-shaft heads and projecting reinforcement occupy the deeper excavation. Larger and smaller excavators stand at different working levels. Retaining walls, access ladders, workers, hoses or cables, uneven benches and a sloping earth route are visible. Machine motion, hose function and final shaft trimming levels cannot be established from a still.</p><h3>8 · Stone handling and rolling</h3><p>A Volvo excavator stands beside a gray crushed-stone stockpile, with a single-drum roller nearby. Gravel covers much of the foreground working area; its extent should not be mistaken for the building footprint.</p></article></div></div>
 <div class="cutting-grid"><figure><img loading="lazy" src="images/annotated/IMG_0128.svg" alt="Labeled close overview of crane outriggers, mobile office, gravel, shaft heads and the near excavation edge"><figcaption>The closer view connects the new office with the previously prepared eastern surface. <a class="photo-original" href="images/originals/IMG_0128.jpeg">View original photograph</a></figcaption></figure><article class="card"><div class="status observed">Observer confirmed</div><h3>2 · The new eastern site office</h3><p>The rectangular mobile office is now established at the eastern end closest to the observer. The observer confirms that it was placed on the plastic sheet and rolled gravel documented on October 2. This closes the earlier uncertainty about the prepared area's use; it is the office base.</p><div class="status likely">Visual interpretation</div><h3>7 · The building's extent becomes easier to picture</h3><p>The observer can now use the near edge of the deep excavation to begin judging how far the future building will stand from their viewpoint. The pit boundaries and exposed foundation pattern provide a much clearer spatial reference.</p><p>The marked excavation edge is approximate. The eventual facade may sit inside or otherwise differ from that edge. No numerical separation, surveyed footprint or final building line is assigned from these photographs.</p></article></div>
 <figure style="margin:28px 0"><img loading="lazy" src="images/annotated/october5-office-section.svg" alt="Conceptual section from observer side across the eastern office base to the deep excavation; final facade location and separation are unmeasured"><figcaption style="padding-top:12px;color:var(--muted)">Conceptual relationship only, not a measured section. The mobile office base and the deep excavation serve different functions.</figcaption></figure>
 <p class="note"><b>What changed in our interpretation:</b> the October 2 plastic sheet, gravel spreading and rolling are now linked to the installed mobile office. The crane's next lift and future horizontal foundation reinforcement will provide the next clues about the structural sequence.</p></div>`;
 document.querySelector('#update-oct2').before(section);
 const nav=document.querySelector('.nav .wrap');const link=document.createElement('a');link.href='#update-oct5';link.textContent='October 5';nav.insertBefore(link,nav.querySelector('a'));
 section.querySelectorAll('img').forEach(img=>img.addEventListener('click',()=>openLightbox(img.src,img.alt)));
})();
