(()=>{
  const section=document.createElement('section');
  section.id='latest';section.className='section';
  section.innerHTML=`<div class="wrap">
    <div class="eyebrow">Field update · September 15–16, 2026</div>
    <h2>From temporary casing<br>to exposed shaft head.</h2>
    <p class="lede">The latest observations complete a construction story that began with casing installation weeks ago. As excavation deepens, upper steel casing is cut away in sections, moved aside and flattened for recycling. What remains is the concrete drilled-shaft head with projecting reinforcement, ready for the next structural connection.</p>
    <div class="cutting-grid">
      <figure><img loading="lazy" src="images/annotated/IMG_6266.svg" alt="Annotated September 15 photo locating cutting sparks, remaining steel casing, exposed concrete and perimeter shoring"><figcaption>September 15 supplied the missing evidence: active cutting at the exposed casing.<br><a class="photo-original" href="images/originals/IMG_6266.JPG" target="_blank" rel="noopener">Inspect original photograph</a></figcaption></figure>
      <div class="haulage-copy">
        <article class="card"><div class="status observed">Observed</div><h3>The casing lifecycle is now visible</h3><p>Earlier photographs showed casing being installed around drilled shafts. Later views showed progressively longer casing lengths exposed by excavation. September 15 directly showed cutting sparks and opened steel shells. The September 16 site observation adds the next stage: separated casing sections lying horizontally while more concrete shaft heads and projecting reinforcement are exposed.</p><div class="status observed">Observed</div><p>The site observer has repeatedly seen removed casing sections flattened by a large excavator, loaded into bins or dump trucks and hauled away for recycling. Recycling is therefore treated as an observed part of the casing-removal sequence, not an inference.</p><div class="status unknown">Still unknown</div><p>These observations establish removal of the exposed upper casing, but not the role of any casing retained deeper below grade. Project drawings would be needed to determine whether retained lower casing has a structural role.</p></article>
        <p class="note"><b>What changed in our interpretation:</b> the journal originally left the casing question open. Scrap later suggested cutback; September 15 confirmed active cutting; the September 16 observations now connect cutting, separated casing sections, flattening, haul-away and recycling into one observed sequence.</p>
      </div>
    </div>
    <div class="cutting-grid">
      <figure><img loading="lazy" src="images/annotated/IMG_6271.svg" alt="Annotated concrete shaft heads with projecting vertical and circular reinforcement, cut casing edges and nearby gas cylinders"><figcaption>Once the upper shell is opened, the permanent concrete shaft head and projecting reinforcement become much easier to read.<br><a class="photo-original" href="images/originals/IMG_6271.JPG" target="_blank" rel="noopener">Inspect original photograph</a></figcaption></figure>
      <div class="haulage-copy">
        <figure><img loading="lazy" src="images/annotated/IMG_6268.svg" alt="Annotated site overview showing the casing-cutting area, removed steel segments, exposed casings and perimeter shoring"><figcaption>The wider view shows why the shafts seem to 'grow' out of the ground: the surrounding soil is being excavated away.</figcaption></figure>
        <article class="card"><h3>Not columns yet</h3><p>The exposed circular concrete elements are best described at this stage as <b>drilled-shaft heads</b> or foundation shafts, not building columns. Deeper excavation is uncovering them and their projecting reinforcement. The next decisive clue will be horizontal reinforcement and concrete connecting these shaft heads into pile caps, grade beams, a mat, or some combination.</p><p>The apparent transformation is therefore: <b>buried drilled shaft → deeper excavation → exposed casing → casing cutback → exposed concrete shaft head and rebar → future structural connection.</b></p></article>
      </div>
    </div>
    <details class="guide-item"><summary><span class="guide-title">Why the new evidence matters</span><span class="guide-chevron">+</span></summary><div class="guide-body"><p><b>Observed:</b> deeper excavation, active casing cutting, separated casing shells, concrete shaft heads, projecting reinforcement, flattening and removal of casing steel for recycling. <b>Likely:</b> the excavation is approaching elevations needed for the next foundation-connection work. <b>Unknown:</b> exact cutoff elevations, retained lower-casing function, concrete acceptance details and the final cap/mat/grade-beam arrangement.</p><img loading="lazy" src="images/annotated/IMG_6272.svg" alt="Annotated casing corridor identifying casing 48, casing 49, shoring and gas equipment"><p>The important lesson is chronological: each new photograph can upgrade an earlier hypothesis into an observation or overturn it entirely.</p></div></details>
  </div>`;
  document.querySelector('#history').before(section);
  const nav=document.querySelector('.nav .wrap');const link=document.createElement('a');link.href='#latest';link.textContent='Latest update';nav.insertBefore(link,nav.querySelector('a'));
  section.querySelectorAll('img').forEach(img=>img.addEventListener('click',()=>openLightbox(img.src,img.alt)));
})();
